In [1]:
pip install ucimlrepo

Note: you may need to restart the kernel to use updated packages.


In [5]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
import numpy as np
from tensorflow.keras import models, layers

# Fetch dataset
optical_recognition_of_handwritten_digits = fetch_openml(name='optdigits', version=1, as_frame=False)

# Data preprocessing
X = optical_recognition_of_handwritten_digits.data.astype(np.float32)
X /= 255.0  # Normalize the data
X = X.reshape(-1, 8, 8, 1)  # Reshape the data
y = LabelBinarizer().fit_transform(optical_recognition_of_handwritten_digits.target)

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

# Define the CNN model
model = models.Sequential()

# Convolutional layers
model.add(layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(8, 8, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu', padding='same'))

# Fully connected layers
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.1)

# Evaluate the model
test_loss, test_acc = model.evaluate(X_test, y_test)
print('Test accuracy:', test_acc)


Epoch 1/5
72/72 [==============================] - 2s 15ms/step - loss: 2.0948 - accuracy: 0.3489 - val_loss: 1.3755 - val_accuracy: 0.6798
Epoch 2/5
72/72 [==============================] - 1s 11ms/step - loss: 0.7771 - accuracy: 0.7601 - val_loss: 0.5773 - val_accuracy: 0.7925
Epoch 3/5
72/72 [==============================] - 1s 12ms/step - loss: 0.4177 - accuracy: 0.8684 - val_loss: 0.3180 - val_accuracy: 0.9091
Epoch 4/5
72/72 [==============================] - 1s 12ms/step - loss: 0.2881 - accuracy: 0.9154 - val_loss: 0.2224 - val_accuracy: 0.9269
Epoch 5/5
18/18 [==============================] - 0s 4ms/step - loss: 0.2640 - accuracy: 0.9288
Test accuracy: 0.9288256168365479


In [8]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Predictions
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Accuracy
accuracy = accuracy_score(y_true, y_pred_classes)
print("Accuracy:", accuracy)

# Precision
precision = precision_score(y_true, y_pred_classes, average='macro')
print("Precision:", precision)

# Recall
recall = recall_score(y_true, y_pred_classes, average='macro')
print("Recall:", recall)

# F1 Score
f1 = f1_score(y_true, y_pred_classes, average='macro')
print("F1 Score:", f1)

# Confusion Matrix
conf_matrix = confusion_matrix(y_true, y_pred_classes)
print("Confusion Matrix:\n", conf_matrix)


18/18 [==============================] - 0s 3ms/step
Accuracy: 0.9288256227758007
Precision: 0.9338054972968564
Recall: 0.9303490171354225
F1 Score: 0.9305122398292612
Confusion Matrix:
 [[49  0  0  0  1  0  1  0  0  0]
 [ 0 46  0  0  0  0  0  0  3  3]
 [ 1  0 53  0  0  0  0  0  0  0]
 [ 0  0  0 53  0  2  0  0  6  0]
 [ 0  1  0  0 50  0  1  0  1  0]
 [ 0  0  2  0  1 50  0  0  0  2]
 [ 0  1  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0  0 56  2  1]
 [ 0  1  0  0  1  0  0  0 54  0]
 [ 0  0  0  3  2  0  0  0  4 55]]
